/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gigabyte;

import java.awt.BorderLayout;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;
import javax.swing.UIManager;
import views.clientes;
import views.equipos;
import views.mantenimientos;
import views.ordenes;
import views.principal;
import views.tecnicos;

/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        SetDate();
        InitContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void SetDate() {
        LocalDateTime now = LocalDateTime.now();
        Locale spanishLocale = new Locale("es", "ES");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("E dd 'de' MMM", spanishLocale);
        dateText.setText(now.format(formatter));
    }
    
    private void InitContent() {
        ShowJPanel(new principal());
    }
    
    public static void ShowJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p);
        content.revalidate();
        content.repaint();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_prin = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_tecnicos = new javax.swing.JButton();
        btn_equipos = new javax.swing.JButton();
        btn_ordenes_trabajo = new javax.swing.JButton();
        btn_clientes4 = new javax.swing.JButton();
        btn_mantenimientos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        User = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        dateText = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Reparacion de Computadoras");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/iconJFrame.png")).getImage());
        setMinimumSize(new java.awt.Dimension(1050, 660));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(1030, 640));

        menu.setBackground(new java.awt.Color(30, 66, 184));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_2.png"))); // NOI18N

        btn_prin.setBackground(new java.awt.Color(30, 66, 184));
        btn_prin.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_prin.setForeground(new java.awt.Color(255, 255, 255));
        btn_prin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btn_prin.setText("Principal");
        btn_prin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_prin.setBorderPainted(false);
        btn_prin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_prin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_prin.setIconTextGap(13);
        btn_prin.setInheritsPopupMenu(true);
        btn_prin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prinActionPerformed(evt);
            }
        });

        btn_clientes.setBackground(new java.awt.Color(30, 66, 184));
        btn_clientes.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_clientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group.png"))); // NOI18N
        btn_clientes.setText("Clientes");
        btn_clientes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_clientes.setBorderPainted(false);
        btn_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_clientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_clientes.setIconTextGap(13);
        btn_clientes.setInheritsPopupMenu(true);
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        btn_tecnicos.setBackground(new java.awt.Color(30, 66, 184));
        btn_tecnicos.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_tecnicos.setForeground(new java.awt.Color(255, 255, 255));
        btn_tecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/engineering.png"))); // NOI18N
        btn_tecnicos.setText("Tecnicos");
        btn_tecnicos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_tecnicos.setBorderPainted(false);
        btn_tecnicos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_tecnicos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_tecnicos.setIconTextGap(13);
        btn_tecnicos.setInheritsPopupMenu(true);
        btn_tecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tecnicosActionPerformed(evt);
            }
        });

        btn_equipos.setBackground(new java.awt.Color(30, 66, 184));
        btn_equipos.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_equipos.setForeground(new java.awt.Color(255, 255, 255));
        btn_equipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computer.png"))); // NOI18N
        btn_equipos.setText("Equipos");
        btn_equipos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_equipos.setBorderPainted(false);
        btn_equipos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_equipos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_equipos.setIconTextGap(13);
        btn_equipos.setInheritsPopupMenu(true);
        btn_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equiposActionPerformed(evt);
            }
        });

        btn_ordenes_trabajo.setBackground(new java.awt.Color(30, 66, 184));
        btn_ordenes_trabajo.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_ordenes_trabajo.setForeground(new java.awt.Color(255, 255, 255));
        btn_ordenes_trabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/assignment.png"))); // NOI18N
        btn_ordenes_trabajo.setText("Ordenes de Trabajo");
        btn_ordenes_trabajo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_ordenes_trabajo.setBorderPainted(false);
        btn_ordenes_trabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_ordenes_trabajo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ordenes_trabajo.setIconTextGap(13);
        btn_ordenes_trabajo.setInheritsPopupMenu(true);
        btn_ordenes_trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenes_trabajoActionPerformed(evt);
            }
        });

        btn_clientes4.setBackground(new java.awt.Color(30, 66, 184));
        btn_clientes4.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_clientes4.setForeground(new java.awt.Color(255, 255, 255));
        btn_clientes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar_chart.png"))); // NOI18N
        btn_clientes4.setText("Reportes");
        btn_clientes4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_clientes4.setBorderPainted(false);
        btn_clientes4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_clientes4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_clientes4.setIconTextGap(13);
        btn_clientes4.setInheritsPopupMenu(true);
        btn_clientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientes4ActionPerformed(evt);
            }
        });

        btn_mantenimientos.setBackground(new java.awt.Color(30, 66, 184));
        btn_mantenimientos.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        btn_mantenimientos.setForeground(new java.awt.Color(255, 255, 255));
        btn_mantenimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hardware.png"))); // NOI18N
        btn_mantenimientos.setText("Mantenimientos");
        btn_mantenimientos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 13, 1, 1, new java.awt.Color(0, 0, 0)));
        btn_mantenimientos.setBorderPainted(false);
        btn_mantenimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_mantenimientos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_mantenimientos.setIconTextGap(13);
        btn_mantenimientos.setInheritsPopupMenu(true);
        btn_mantenimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mantenimientosActionPerformed(evt);
            }
        });

        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 5));

        User.setBackground(new java.awt.Color(255, 255, 255));
        User.setFont(new java.awt.Font("Caviar Dreams", 3, 14)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));
        User.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account_circle.png"))); // NOI18N
        User.setText("Usuario");
        User.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        User.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 10, 1));

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btn_prin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_mantenimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_clientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_ordenes_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_prin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(btn_mantenimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btn_tecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btn_clientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(User, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btn_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btn_ordenes_trabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        header.setBackground(new java.awt.Color(25, 118, 210));
        header.setPreferredSize(new java.awt.Dimension(744, 150));

        dateText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateText.setText("Fecha");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateText, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        content.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prinActionPerformed
        ShowJPanel(new principal());
    }//GEN-LAST:event_btn_prinActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new clientes());
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_tecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tecnicosActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new tecnicos());
    }//GEN-LAST:event_btn_tecnicosActionPerformed

    private void btn_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equiposActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new equipos());
    }//GEN-LAST:event_btn_equiposActionPerformed

    private void btn_ordenes_trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenes_trabajoActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new ordenes());
    }//GEN-LAST:event_btn_ordenes_trabajoActionPerformed

    private void btn_clientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clientes4ActionPerformed

    private void btn_mantenimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mantenimientosActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new mantenimientos());
    }//GEN-LAST:event_btn_mantenimientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatIntelliJLaf");
            UIManager.put("TabbedPane.underlineColor", new java.awt.Color(30, 57, 50));

        } catch (Exception ex) {
            System.out.println("Librería FlatLaf no encontrada. Cargando tema por defecto...");

            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                System.out.println("No se pudo cargar el tema del sistema.");
            }
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel User;
    private javax.swing.JPanel background;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_clientes4;
    private javax.swing.JButton btn_equipos;
    private javax.swing.JButton btn_mantenimientos;
    private javax.swing.JButton btn_ordenes_trabajo;
    private javax.swing.JButton btn_prin;
    private javax.swing.JButton btn_tecnicos;
    private static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
